### ISSUE TITLE
Refactor idea route to include :space_id param

### ISSUE THREAD

**Issue by ac524** [jmichaelbrown8/elevator-pitch#43]
To enforce membership authentication, the route `/idea/:id` needs to be updated to `/space/:space_id/idea/:idea_id`.

- [x] Update route in `homeRoutes.js`.
- [x] Update links in view files to correctly point the new idea page route.

**Comment by kimberlym4488** [comment]
Resolved in PR #45 - home route and view files updated properly to space/:space_id/idea/:idea_id withMembershipAuth. Routes functioning as expected.
