### ISSUE TITLE
Feature / Create Resource User Flow and UI

### ISSUE THREAD

**Issue by ac524** [jmichaelbrown8/elevator-pitch#61]
- [x] Implement Multer package to allow user to upload images, links, etc. 
- [ ] Test functionality
- [ ] Test uploaded data appears in idea detail page.

**Comment by kimberlym4488** [comment]
May I update the figma for you on this one?

**Comment by kimberlym4488** [comment]
These cards look amazing!

**Comment by kimberlym4488** [comment]
#91
